package com.enet.sab.ui.view

enum class LunchActivity (val value:String){
    activate("Active"),
    login("Login"),
    chengPassword("ChengPassword"),
    import("Import"),
    home("Home"),
    addUser("AddUser"),
    editUser("EditUser"),
    viewUser("ViewUser"),
    usersList("UsersList"),
    addUnit("AddUnit"),
    editUnit("EditUnit"),
    viewUnitHistory("viewUnitHistory"),
    unitsList("UnitsList"),
    addGroup("AddGroup"),
    editGroup("EditGroup"),
    viewGroupHistory("ViewGroupHistory"),
    groupsList("GroupsList"),
    addReport("AddReport"),
    editReport("EditReport"),
    viewReport("ViewReport"),
    reportsList("ReportsList"),
    addCoast("AddCoast"),
    editCoast("EditCoast"),
    viewCoast("ViewCoast"),
    coastsList("CoastsList"),
    addContact("AddContact"),
    editContact("EditContact"),
    viewContact("ViewContact"),
    contactsList("ContactsList"),

}